import { css } from "@emotion/css";
import type { NextPage } from "next";
import Head from "next/head";

const appStoreLink =
  "https://apps.apple.com/jp/app/%E3%83%AB%E3%83%BC%E3%83%AC%E3%83%83%E3%83%88/id1405862584";

const playStoreLink =
  "https://play.google.com/store/apps/details?id=com.churabou.roulette&hl=ja&gl=US";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ルーレット!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen pb-14 bg-right bg-cover">
        <div className="container pt-24 md:pt-48 px-12 mx-auto flex flex-wrap flex-col md:flex-row items-center">
          <div
            className={css`
              padding: 48px;
            `}
          >
            <h1
              className={css`
                background: linear-gradient(to right bottom, #058ef8, #02eefe);
                background-clip: text;
                color: transparent;
                font-size: 48px;
                font-weight: bold;

                padding-top: 24px;
                padding-bottom: 24px;
              `}
            >
              迷ったときのルーレット!
            </h1>
            <p
              className={css`
                font-size: 20px;
                line-height: 1.8;
              `}
            >
              ルーレット!はシンプルなルーレットアプリです。
              <br />
              ランチやお出かけ先など迷ったときに使ってみてください。
            </p>
            <div>
              <p
                className={css`
                  padding-top: 16px;
                  padding-bottom: 16px;
                `}
              >
                アプリをダウンロード
              </p>
              <div
                className={css`
                  height: 50px;
                  justify-content: center;
                  a {
                    display: inline-block;
                    img {
                      height: 50px;
                    }

                    &:first-child {
                      margin-right: 12px;
                    }
                  }
                `}
              >
                <a href={appStoreLink}>
                  <img src="app_store.svg" className="h-12 pr-4" />
                </a>
                <a href={playStoreLink}>
                  <img src="play_store.svg" className="h-12 pr-4" />
                </a>
              </div>
            </div>
          </div>
          <div
            className={css`
              margin: 0px auto;
            `}
          >
            <img
              className={css`
                width: 300px;
              `}
              src="./preview1.png"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
