import type { NextPage } from "next";
import Head from "next/head";

const appStoreLink =
  "https://apps.apple.com/jp/app/%E3%83%AB%E3%83%BC%E3%83%AC%E3%83%83%E3%83%88/id1405862584";

const playStoreLink =
  "https://play.google.com/store/apps/details?id=com.churabou.roulette&hl=ja&gl=US";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ルーレット!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen pb-14 bg-right bg-cover">
        <div className="container pt-24 md:pt-48 px-12 mx-auto flex flex-wrap flex-col md:flex-row items-center">
          <div className="flex flex-col w-full xl:w-2/5 justify-center lg:items-start overflow-y-hidden">
            <h1 className="my-8 text-3xl md:text-5xl text-title-gradient font-bold leading-tight text-center md:text-left ">
              迷ったときのルーレット!
            </h1>
            <p className="leading-normal text-base md:text-md mb-8 text-center md:text-left">
              ルーレット!はシンプルなルーレットアプリです。
              ランチ、お出かけ先など迷ったときに使ってみてください。
              いろんなところ使えて意外と便利です。
            </p>

            <p className="text-blue-400 font-bold pb-8 lg:pb-6 text-center md:text-left">
              Download our app:
            </p>
            <div className="flex w-full justify-center md:justify-start pb-24 lg:pb-0">
              <a href={appStoreLink}>
                <img src="app_store.svg" className="h-12 pr-4" />
              </a>
              <a href={playStoreLink}>
                <img src="play_store.svg" className="h-12 pr-4" />
              </a>
            </div>
          </div>

          <div className="w-full xl:w-3/5 py-6">
            <img className="w-80 mx-auto mt-4 lg:mr-0" src="./preview1.png" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
